name: 04 - Using Actions
on: 
    push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              run: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install Dependencies
              run: npm install
            - name: Printing Folders
              run: ls
