name: 08 - Using Variables
on: 
    push
env:
    WORKFLOW_VAR: "I am a Workflow env"
    OVERWRITTEN: " I will be overwritten"
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a job var"
            OVERWRITTEN:  " I have been overwritten at the job level"
        steps:
            - name: Print Env Variables
              env:
                STEP_VAR: "I am a step env var"
                STEP_VAR2: "I am a another env var"
              run: |
                echo " Step env var: ${{env.STEP_VAR}}"
                echo "Step env var 2: ${{env.STEP_VAR2}}"
                echo "Job env: ${{env.JOB_VAR}}"
                echo "Workflow env var: ${{env.WORKFLOW_VAR}}"                
                echo "Overwritten env var: ${{env.OVERWRITTEN}}"
            - name: Overwrite Job Variable
              env: 
                OVERWRITTEN: "I have been Overwritten at the step level"
              run: |
                echo "Overwritten env var: ${{env.OVERWRITTEN}}"
